### ISSUE TITLE
No_Return on access-to-subp type?

### ISSUE THREAD

**Issue by sttaft** [Ada-Rapporteur-Group/User-Community-Input#1]
We have a need to associate the "No_Return" aspect with an access-to-subprogram type.  Given how important is the No_Return notion, that seems reasonable.  I presume the matching would be such that only No_Return subprograms can be designated by a value of a No_Return access-to-subp type, but any sort of subprogram (including No_Return ones) could be designated by a value of an access-to-subp type whose No_Return aspect is False.

**Comment by Richard-Wai** [comment]
This seems like a fairly strait-forward feature for most cases, but I am curious about run-time checks. Would this cause an accessibility check to fail, or would it cause a Constraint_Error or Progam_Error?

In some senses it seems even having the threat of such exceptions for such a relatively rarely used feature might be excessive. Should we consider maybe attaching an additional requirement that all assignments to such types be static?

**Comment by sttaft** [comment]
This would be a legality rule.  No additional run-time checks are involved.

Note that there is *already* a run-time check inside a procedure or function with a No_Return aspect True, which ensures they never return normally.  This suggestion is simply allowing you to declare an access type that you know will only designate subprograms that never return normally (will loop forever or propagate an exception on every call).

**Comment by ARG-Editor** [comment]
AI22-0090-1 has been created for this issue.

**Comment by ARG-Editor** [comment]
AI22-0090-1 has been approved by the ARG during meeting #63B, so this issue has been closed.
