### ISSUE TITLE
Named parameters in reduction expression

### ISSUE THREAD

**Issue by sttaft** [Ada-Rapporteur-Group/User-Community-Input#13]
!reference Ada 202x RM4.5.10(23/5)
!from Chrisoph Grein 2021-07-17
!keywords named parameter notation
!discussion

I've always liked the named parameter notation and use it always when it adds information like e.g. in `Put (I, Width => 42)`, I hate to see calls like `Put (X, 2, 3)`. I however use it never in cases where the actual and formal parameter have the same name - that's just noise - with one important exception: in cases like Arctan where calls with positional notation lose important information (here the coordinates, especially so as parameters are called y, x in this sequence).

To come to the point. Reduction expression are missing this feature and are less readable:
       ` My_Rates'Reduce (Float'Min, Float'Last)`
and I can easily dream up more cryptic expressions.

I'm very well aware of the problems: There is no way in Ada to use subprograms as parameters (only as access). What is more: Operators used in such expressions may be intrinsic, so they have not access.

So in the syntax proposed, there is a lot of magic involved. ... Perhaps ARG ingenuity can come up with a solution.

Christoph

**Comment by ARG-Editor** [comment]
This topic is included in AI22-0081-1.

**Comment by ARG-Editor** [comment]
AI22-0081-1 was Approved by the ARG at meeting #63A, so this issue has been closed.
