### ISSUE TITLE
Ada.Calendar.Formatting.Day_Of_Week should have a Time_Zone parameter

### ISSUE THREAD

**Issue by sttaft** [Ada-Rapporteur-Group/User-Community-Input#17]
Ada.Calendar.Formatting.Day_of_Week  does not account for the Time_Zone... unlike every other formatting function in the same package, including the Day function.

---

Ada.Calendar.Formatting.Day_of_Week needs to have a Time_Zone parameter like all the others.  It should default to 0 (UTC) like all the others...

The LRM doesn't comment on what time zone would currently be used (local or UTC), so it isn't possible to say whether using 0 as a default would be backwards compatible with implementations, but that just underscores the need for more clarity.

Joshua Fletcher, fletcher.ua@gmail.com, 7/19/2022 15:08:12

**Comment by ARG-Editor** [comment]
AI22-0048-1 has been created for this issue.

**Comment by ARG-Editor** [comment]
AI22-0048-1 is now both ARG and WG 9 approved.
