### ISSUE TITLE
Ada.Unchecked_Deallocate_Subpool needs Preelaborate aspect

### ISSUE THREAD

**Issue by sttaft** [Ada-Rapporteur-Group/User-Community-Input#20]
It would be useful if the Preelaborate aspect were set to True for Ada.Unchecked_Deallocate_Subpool (Ada RM 13.11.5).  The package System.Storage.Subpools has Preelaborate True, so there seems no reason that this procedure shouldn't as well.

-----

Maxim Reznik | reznikmm@gmail.com | 8/16/2022 13:35:12

**Comment by ARG-Editor** [comment]
This seems like an oversight. I've made AI22-0050-1 for this issue.

**Comment by ARG-Editor** [comment]
AI22-0050-1 was approved at the ARG's November 2022 meeting.
