### ISSUE TITLE
Small typo in AARM 202x 4.1 17.e

### ISSUE THREAD

**Issue by okellogg** [Ada-Rapporteur-Group/User-Community-Input#23]
In draft 33 of the Ada 202x Annotated Reference Manual [section 4.1](http://www.ada-auth.org/standards/2xaarm/html/AA-4-1.html) at end of para 17.e,

> Note that these rules [...], so we don't need to use prefix to allow functions calls in front of .all.

I believe "functions calls" should be "function calls".

**Comment by ARG-Editor** [comment]
You found a bug in the original Ada 95 AARM. It's amazing that after 27 years, people still find them. Anyway, since this is a simple bug in an AARM note, this issue will be added to AI12-0005-1 and the correction made in the final version of Ada 2022.
