### ISSUE TITLE
Minor formatting issues in Ada202x Annex P Syntax Rules

### ISSUE THREAD

**Issue by okellogg** [Ada-Rapporteur-Group/User-Community-Input#24]
In draft 33 of the Ada 202x Annex P [Syntax Rules](http://www.ada-auth.org/standards/2xaarm/html/AA-P-1.html)

> ```
> 6.5
> extended_return_object_declaration ::=
>     defining_identifier : [aliased][constant] return_subtype_indication [:= expression]
>         [aspect_specification]
> ```

At `[aliased][constant]` insert space between `][`.
    
> ```
> 9.1
> single_task_declaration ::= 
>    task defining_identifier
>         [aspect_specification][is
>      [new interface_list with]
>      task_definition];
> ```

At `[aspect_specification][is` insert space between `][`.
  
> ```
> 12.5.1
> formal_derived_type_definition ::=
>     [abstract] [limited | synchronized] new subtype_mark [[and interface_list]with private]
> ```
   
At `[and interface_list]with private` insert space between `]` and `with`.

**Comment by ARG-Editor** [comment]
The syntax rules are synthesized from the definitions scattered throughout the RM, so you *really* want to reformat these definitions in 6.5, 9.1, and 12.5.1. The only thing unique to annex P is the introductory sentences.

**Comment by ARG-Editor** [comment]
I've added these to AI12-0446-1 (some presentation issues to correct in the final Ada 2022 RM), and it will be on the agenda for the upcoming ARG meeting.

**Comment by ARG-Editor** [comment]
At least I'm trying to close this issue as completed...

**Comment by okellogg** [comment]
Thanks.
