### ISSUE TITLE
Conversion from Big Reals to Decimal Fixed

### ISSUE THREAD

**Issue by sttaft** [Ada-Rapporteur-Group/User-Community-Input#39]
A colleague at AdaCore noticed that Big_Numbers.Big_Reals has generics for converting to floating point and "ordinary" fixed point, but not to decimal fixed point.  In other places in the standard where we have a generic for both floating point and ordinary fixed, we generally include an analogous generic for decimal fixed point (e.g. Text_IO).  This seems like an oversight which would be extremely easy to fix.  Obviously not super important!

**Comment by ARG-Editor** [comment]
This issue is addressed in AI22-0078-1 (which will be available shortly).

**Comment by ARG-Editor** [comment]
AI22-0078-1 has been approved.
