### ISSUE TITLE
Install Slack Application

### ISSUE THREAD

**Issue by reznikmm** [Ada-Rapporteur-Group/User-Community-Input#43]
Could you enable Slack integration application on this repo? It helps users to monitor repo activity with Slack (not just by email),

https://github.com/apps/slack/installations/new

**Comment by sttaft** [comment]
Hi Max,
    Can you explain the process a bit more?  When I click the above link, it doesn't mention this GitHub repo.  Perhaps I would need to be an owner or manager of the repo to do this.  I have forwarded your request to Richard Wai who created this Ada-Rapporteur-Group repo.
Thanks,
-Tuck

**Comment by Richard-Wai** [comment]
Hi Max, sorry I missed this. I believe I have completed this action. Please let me know if that works!

**Comment by reznikmm** [comment]
`/github subscribe Ada-Rapporteur-Group/User-Community-Input` works fine now. Thank you!
