### ISSUE TITLE
Ask ARG members not to close issues

### ISSUE THREAD

**Issue by sttaft** [Ada-Rapporteur-Group/User-Community-Input#48]
The Readme should probably be augmented with an indication that ARG members should not close issues.  I.e., when making a comment, simply choose "Comment" rather than "Comment and Close Issue".  Probably only Randy or Richard should close issues in the ARG GitHub repository.

https://github.com/Ada-Rapporteur-Group/User-Community-Input/blob/65c28351d1c4ed91b0f968f35cab9e0efa4c64b4/README.md?plain=1#LL46C1-L46C13

**Comment by Richard-Wai** [comment]
Added a paragraph to this effect in the most recent README.md update pull request, under heading "Direct Induction of Issues by the ARG".
