### ISSUE TITLE
Pattern Matching comments.

### ISSUE THREAD

**Issue by Blady-Com** [Ada-Rapporteur-Group/User-Community-Input#56]
Here are some comments on [Rigorous Pattern Matching as a Language Feature](https://drive.google.com/file/d/14SMQLsMdRKbsmgBz5Je1l9zFRx85Rdce/view?usp=drive_web):
2.2 Proposed Pattern Matching Syntax
```
simple_pattern ::=
[identifier :] unlabeled_pattern
| <identifier>
```
might be
```
simple_pattern ::=
[<identifier> :] unlabeled_pattern
| <identifier>
```
in oder to have a same syntaxe in both cases, for instance :
`<Val>:(0 .. 100 with mod 2 => 0, mod 3 => 1)`
```
unlabeled_pattern ::=
<>
| static_expression
| static_range
| subtype_mark
| property_pattern
| sequence_pattern
| map_pattern
```
might be
```
unlabeled_pattern ::=
<>
| static_expression
| static_range
| subtype_mark
| property_pattern
| sequence_pattern
| map_pattern
| [not] null
```
in order to match accesses for instance:
```
case Panel, Button is
  when not null, not null => Panel.Toggle (Button);
  when not null, null => Panel.Create (Button);
  when others => raise GUI_Error;
end case;
```
```
sequence_pattern ::=
[ pattern [*|+]{,
pattern [*|+]} [, others => pattern] ]
```
might be
```
sequence_pattern ::=
[ pattern [*|+]{,
pattern [*|+]} [, others => pattern [+]] ]
```
in order to specify that the `others` part shall match at least once for instance:
`[’0’, ’x’ | ’X’, others => ’0’..’9’ | ’a’ .. ’f’ | ’A’ .. ’F’ +]`

**Comment by sttaft** [comment]
Thank you for the comments!  I have copied your comment to Issue #34 on Pattern Matching as an Ada Language Feature to avoid splitting the discussion on pattern matching between two issues.  Please continue the discussion there.

**Comment by ARG-Editor** [comment]
I've closed this issue to further discourage commenting on it, as well as marked it as a duplicate.
