### ISSUE TITLE
Does "@" ever statically denote an object?

### ISSUE THREAD

**Issue by sttaft** [Ada-Rapporteur-Group/User-Community-Input#6]
There are various rules that depend on whether a name statically denotes some declaration.  If the LHS of an assignment statically denotes a declaration, can we presume that an "@" used on the RHS also statically denotes the same declaration?

**Comment by Jeff-Cousins** [comment]
I hope so.On 10 Jun 2022 16:22, sttaft ***@***.***> wrote:
There are various rules that depend on whether a name statically denotes some declaration.  If the LHS of an assignment statically denotes a declaration, can we presume that an "@" used on the RHS also statically denotes the same declaration?

**Comment by ARG-Editor** [comment]
This seems like a language bug that needs an AI write-up. I have another issue with statically denotes that also needs a write-up, should I combine those?

**Comment by ARG-Editor** [comment]
This question was answered by AI12-0332-1; 4.9(16.1/5) says that it does statically denote an object.

However, Tucker might have been referring to my private question of whether it statically NAMES an entity that is not statically denoted. This is now the subject of AI22-0046-1 (see the active AI list).

**Comment by ARG-Editor** [comment]
AI12-0046-1 was approved at the June 2022 ARG meeting (#62Q), so I've closed this question.
