### ISSUE TITLE
Multidimensional array aggregates with outer iterator loop parameter used in subaggregate

### ISSUE THREAD

**Issue by sttaft** [Ada-Rapporteur-Group/User-Community-Input#64]
Currently the following multidimensional array aggregate is not explicitly illegal, as far as I can tell:

```
   type Arr is array (Positive range <>, Positive range <>) of Integer;
   X : Arr := [for I in 1 .. 0 => [for J in I .. I + 1 => 42]];
```
However, this seems to interfere with RM 4.3.3(22):

> Any [discrete_choice](http://www.ada-auth.org/standards/22aarm/html/AA-3-8-1.html#S0074)s of this aggregate and of its subaggregates are evaluated in an arbitrary order, and converted to the corresponding index type;

which seems to require that we evaluate all of the discrete_choices even for a null array, and in an arbitrary order, which is not possible given the dependence of the range of J on the value of the index parameter I.

It would seem we need to disallow the use of an outer dimension index parameter in a discrete_choice or iterator_specification of a nested subaggregate.  We might modify 4.3.3(17) as follows:

> The [discrete_choice_list](http://www.ada-auth.org/standards/22aarm/html/AA-3-8-1.html#S0073) of an [array_component_association](http://www.ada-auth.org/standards/22aarm/html/AA-4-3-3.html#S0118) (including an [iterated_component_association](http://www.ada-auth.org/standards/22aarm/html/AA-4-3-3.html#S0119)) is allowed to have a [discrete_choice](http://www.ada-auth.org/standards/22aarm/html/AA-3-8-1.html#S0074) that is a nonstatic [choice_expression](http://www.ada-auth.org/standards/22aarm/html/AA-4-4.html#S0133) or that is a [subtype_indication](http://www.ada-auth.org/standards/22aarm/html/AA-3-2-2.html#S0027) or [range](http://www.ada-auth.org/standards/22aarm/html/AA-3-5.html#S0037) that defines a nonstatic or null range, only if it is the single [discrete_choice](http://www.ada-auth.org/standards/22aarm/html/AA-3-8-1.html#S0074) of its [discrete_choice_list](http://www.ada-auth.org/standards/22aarm/html/AA-3-8-1.html#S0073), and either there is only one [array_component_association](http://www.ada-auth.org/standards/22aarm/html/AA-4-3-3.html#S0118) in the enclosing [array_component_association_list](http://www.ada-auth.org/standards/22aarm/html/AA-4-3-3.html#S0117) or the enclosing [aggregate](http://www.ada-auth.org/standards/22aarm/html/AA-4-3.html#S0106) is an [array_delta_aggregate](http://www.ada-auth.org/standards/22aarm/html/AA-4-3-4.html#S0122)[Redundant:, not an [array_aggregate](http://www.ada-auth.org/standards/22aarm/html/AA-4-3-3.html#S0113)]._{  In a multidimensional array aggregate, a name denoting an index parameter of an iterated_component_association of an array aggregate shall not occur within a discrete_choice_list or iterator_specification of a subaggregate of the aggregate.}_

**Comment by evanescente-ondine** [comment]
Currently this produces on my machine the bug report below:
> drm@84-47-09-37-40-35 ~/D/A/A/cs2code> gnatmake test
gcc -c test.adb
+===========================GNAT BUG DETECTED==============================+
| 14.2.0 (x86_64-pc-linux-gnu) GCC error:                                  |
| in gnat_to_gnu_entity, at ada/gcc-interface/decl.cc:464                  |
| Error detected at test.adb:8:45                                          |
| Compiling test.adb                                                       |
| Please submit a bug report; see https://gcc.gnu.org/bugs/ .              |
| Use a subject line meaningful to you and us to track the bug.            |
| Include the entire contents of this bug box in the report.               |
| Include the exact command that you entered.                              |
| Also include sources listed below.                                       |
+==========================================================================+
Please include these source files with error report
Note that list may not be accurate in some cases,
so please double check that the problem can still
be reproduced with the set of files listed.
Consider also -gnatd.n switch (see debug.adb).
test.adb
compilation abandoned
gnatmake: "test.adb" compilation error

gnat_native=14.2.1
Linux 84-47-09-37-40-35 6.10.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.11-1 (2024-09-22) x86_64 GNU/Linux

**Comment by sttaft** [comment]
This will become illegal is my guess.   More generally, GNAT currently has some problems with multidimensional array aggregates when the bounds are not constants, though that bug is being worked on I believe.  But the above example will hopefully be recognized as illegal in the near future.

**Comment by sttaft** [comment]
Steve Baird checked that the latest GNAT gives the following appropriate error messages:
$ cat bad_agg.ads
```
package Bad_Agg is
   type Arr is array (Positive range <>, Positive range <>) of Integer;
   X : Arr := [for I in 1 .. 0 => [for J in I .. I + 1 => 42]];
end Bad_Agg;

```
$ gcc -c -gnat2022 bad_agg.ads
```
bad_agg.ads:3:45: error: bound expression for a subaggregate of an array aggregate must not refer to an index parameter of an earlier dimension
bad_agg.ads:3:50: error: bound expression for a subaggregate of an array aggregate must not refer to an index parameter of an earlier dimension
```

Apparently AI22-0106 was implemented a while ago, which requires this behavior.

**Comment by ARG-Editor** [comment]
AI22-0106-1 addressed this issue, and it was approved in July 2024, so I have closed this issue.
